from google import genai
import json
import os
import time

API_KEY = os.getenv("GEMINI_API_KEY")

if not API_KEY:
    raise RuntimeError("GEMINI_API_KEY is not set.")

client = genai.Client(api_key=API_KEY)

# Try models in this order
MODELS = [
    "gemini-3.8-flash",
    "gemini-3.7-flash",
    "gemini-3.6-flash",
    "gemini-3.5-flash",
    "gemini-3.1-flash-lite",
]


def ask_llm(prompt):
    """
    Try available Gemini models until one responds.
    """

    errors = []

    for model in MODELS:

        try:
            print(f"Trying Gemini model: {model}")

            response = client.models.generate_content(
                model=model,
                contents=prompt
            )

            if response.text:
                print(f"Gemini model working: {model}")
                return response.text

        except Exception as e:

            error = str(e)
            errors.append(f"{model}: {error}")

            # Try the next model for temporary availability errors
            if "503" in error or "UNAVAILABLE" in error:
                continue

            # Try another model for other model-specific errors too
            continue

    return (
        "Gemini is temporarily unavailable.\n\n"
        "Models attempted:\n"
        + "\n".join(errors)
    )


def explain_supply_chain(result):

    prompt = f"""
You are a responsible AI assistant for a
supply-chain decision-support system.

Your task is to explain the results generated by
the SupplyChain-Swarm simulation.

RESPONSIBLE AI RULES:

1. Use ONLY the information provided in the simulation result.
2. Never invent supplier names, costs, quantities, risks,
   inventory values, or other business information.
3. Do not claim that a simulated recommendation is a real
   procurement order.
4. Clearly state when information is simulated.
5. Do not make decisions outside the information provided.
6. Explain assumptions when they are relevant.
7. If information is missing, say that it is unavailable.
8. A human should review any recommendation before
   real-world procurement action.

SUPPLYCHAIN-SWARM RESULT:

{json.dumps(result, indent=2, default=str)}

Provide a concise explanation using these sections:

1. Situation
2. Inventory Analysis
3. Supplier Analysis
4. Procurement Decision
5. Recommended Action
6. Important Disclaimer

In the Important Disclaimer, clearly state that
the result is a simulated decision-support recommendation
and requires human review before real-world use.
"""

    return ask_llm(prompt)