import ollama
import json


MODEL = "llama3.2:3b"


def ask_llm(prompt):

    response = ollama.chat(
        model=MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response["message"]["content"]


def explain_supply_chain(result):

    prompt = f"""
You are a responsible AI assistant for a
supply-chain decision-support system.

Your task is to explain the results generated by
the SupplyChain-Swarm simulation.

RESPONSIBLE AI RULES:

1. Use ONLY the information provided in the simulation result.
2. Never invent supplier names, costs, quantities, risks,
   inventory values, or other business information.
3. Do not claim that a simulated recommendation is a real
   procurement order.
4. Clearly state when information is simulated.
5. Do not make decisions outside the information provided.
6. Explain assumptions when they are relevant.
7. If information is missing, say that it is unavailable.
8. A human should review any recommendation before
   real-world procurement action.

SUPPLYCHAIN-SWARM RESULT:

{json.dumps(
    result,
    indent=2,
    default=str
)}

Provide a concise explanation using these sections:

1. Situation
2. Inventory Analysis
3. Supplier Analysis
4. Procurement Decision
5. Recommended Action
6. Important Disclaimer

In the Important Disclaimer, clearly state that
the result is a simulated decision-support recommendation
and requires human review before real-world use.
"""

    return ask_llm(prompt)