import os
import json

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from llm_service import ask_llm


KNOWLEDGE_BASE_DIR = "knowledge_base"


# ==========================================
# LOAD KNOWLEDGE BASE
# ==========================================

def load_documents():

    documents = []

    if not os.path.exists(KNOWLEDGE_BASE_DIR):
        return documents

    for filename in os.listdir(KNOWLEDGE_BASE_DIR):

        if filename.endswith(".txt"):

            filepath = os.path.join(
                KNOWLEDGE_BASE_DIR,
                filename
            )

            with open(
                filepath,
                "r",
                encoding="utf-8"
            ) as file:

                content = file.read()

            documents.append({
                "filename": filename,
                "content": content
            })

    return documents


# ==========================================
# RETRIEVE RELEVANT DOCUMENTS
# ==========================================

def retrieve_documents(query, top_k=2):

    documents = load_documents()

    if not documents:
        return []

    texts = [
        document["content"]
        for document in documents
    ]

    vectorizer = TfidfVectorizer(
        stop_words="english"
    )

    document_vectors = vectorizer.fit_transform(
        texts
    )

    query_vector = vectorizer.transform(
        [query]
    )

    similarities = cosine_similarity(
        query_vector,
        document_vectors
    )[0]

    ranked_indices = similarities.argsort()[::-1]

    results = []

    for index in ranked_indices[:top_k]:

        results.append({

            "filename":
                documents[index]["filename"],

            "content":
                documents[index]["content"],

            "score":
                float(similarities[index])
        })

    return results


# ==========================================
# BUILD RAG CONTEXT
# ==========================================

def build_rag_context(query):

    retrieved_documents = retrieve_documents(
        query,
        top_k=2
    )

    if not retrieved_documents:

        return "No relevant knowledge-base information was found."

    context_parts = []

    for document in retrieved_documents:

        context_parts.append(
            f"""
SOURCE: {document['filename']}
RELEVANCE SCORE: {document['score']:.3f}

{document['content']}
"""
        )

    return "\n".join(context_parts)


# ==========================================
# RAG-POWERED SUPPLY CHAIN ANSWER
# ==========================================

def answer_with_rag(query, supply_chain_result):

    retrieved_documents = retrieve_documents(
        query,
        top_k=2
    )

    if retrieved_documents:

        knowledge_context = "\n\n".join(

            [
                f"""
SOURCE: {document['filename']}

{document['content']}
"""
                for document in retrieved_documents
            ]

        )

    else:

        knowledge_context = (
            "No relevant knowledge-base information was found."
        )


    prompt = f"""
You are an AI assistant for a supply-chain
decision-support system.

You have access to:

1. Retrieved supply-chain policies.
2. Actual results generated by the SupplyChain-Swarm agents.

Your job is to answer the user's question using
ONLY these sources.

IMPORTANT RULES:

- Do not invent supplier information.
- Do not invent costs.
- Do not invent inventory values.
- Do not invent policies.
- Use the retrieved knowledge as supporting information.
- Use the actual agent results for numerical values.
- Clearly distinguish simulated results from real-world decisions.
- If the available information is insufficient, say so.

USER QUESTION:
{query}


RETRIEVED KNOWLEDGE:

{knowledge_context}


SUPPLYCHAIN-SWARM RESULT:

{json.dumps(
    supply_chain_result,
    indent=2,
    default=str
)}


Provide a concise and professional answer.

Also mention which knowledge-base sources were used.
"""

    return ask_llm(prompt)